### ISSUE TITLE
3주차

### ISSUE THREAD

**Issue by JangWooJin1** [Park-Minjoo/CODINGTEST_STUDY#1]
## Description

- 백준 문제 풀이 진행

## Todo

- dp
  - [x] 계단 오르기 https://www.acmicpc.net/problem/2579 - 실버3
  - [x] 징검다리 건너기 https://www.acmicpc.net/problem/21317 - 실버1
  - [x] 스티커 - https://www.acmicpc.net/problem/9465 - 실버1
- 이진탐색
  - [x] 나무 자르기 - https://www.acmicpc.net/problem/2805 - 실버2
- 최단경로
  - [x] 경로 찾기 - https://www.acmicpc.net/problem/11403 - 실버1
