### ISSUE TITLE
5주차

### ISSUE THREAD

**Issue by JangWooJin1** [Park-Minjoo/CODINGTEST_STUDY#10]
## Description

- 백준 문제 복습

## Todo
- [x] 위상 정렬: [음악프로그램](https://www.acmicpc.net/problem/2623) - 골드3
- [x] 크루스칼 알고리즘: [전력난](https://www.acmicpc.net/problem/6497) - 골드4
- [x] 투 포인터: [블로그](https://www.acmicpc.net/problem/21921) - 실버3
- [x] 구간합:  [출석체크](https://www.acmicpc.net/problem/20438) - 실버2
- [x] 소수: [다음 소수](https://www.acmicpc.net/problem/4134) - 실버4
