### ISSUE TITLE
Week27

### ISSUE THREAD

**Issue by yeonkkk** [Park-Minjoo/CODINGTEST_STUDY#100]
## Description

- 프로그래머스

## Todo

- PCCP
  - [ ] [[PCCP 모의고사 #1] 1번 - 외톨이 알파벳](https://school.programmers.co.kr/learn/courses/15008/lessons/121683)
  - [ ] [[PCCP 모의고사 #1] 3번 - 유전법칙](https://school.programmers.co.kr/learn/courses/15008/lessons/121685)

- 완전탐색
  - [ ] [카펫 L2](https://school.programmers.co.kr/learn/courses/30/lessons/42842)
