### ISSUE TITLE
Week28

### ISSUE THREAD

**Issue by yeonkkk** [Park-Minjoo/CODINGTEST_STUDY#104]
## Description
즐겁게 문제를 풀어봐요 !

## Todo

- PCCP
  - [ ] [[PCCP 모의고사 #1] 2번 - 체육대회](https://school.programmers.co.kr/learn/courses/15008/lessons/121684)
  - [ ] [[PCCP 모의고사 #1] 4번 - 운영체제](https://school.programmers.co.kr/learn/courses/15008/lessons/121686)
  - [ ] [[PCCP 기출문제] 1번 / 동영상 재생기](https://school.programmers.co.kr/learn/courses/30/lessons/340213)

- 이진탐색
  - [ ] [입국심사](https://school.programmers.co.kr/learn/courses/30/lessons/43238)
