### ISSUE TITLE
Week29

### ISSUE THREAD

**Issue by Park-Minjoo** [Park-Minjoo/CODINGTEST_STUDY#108]
## Description
우진님 성연님 부재 이슈 .. ~

## Todo

- PCCP
  - [ ] [[PCCP 기출문제] 3번 - 아날로그 시계](https://school.programmers.co.kr/learn/courses/30/lessons/250135)
  - [ ] [[PCCP 기출문제] 4번 - 수레 움직이기](https://school.programmers.co.kr/learn/courses/30/lessons/250134)

- 이진탐색
  - [ ] [휴게소 세우기](https://www.acmicpc.net/problem/1477)

**Comment by leemoongi** [comment]
난이도가 이상합니다..
