### ISSUE TITLE
6주차

### ISSUE THREAD

**Issue by JangWooJin1** [Park-Minjoo/CODINGTEST_STUDY#15]
## Description

- 이코테 마지막 강의 & 문제 풀기

## Todo

- [ ] [우선순위 큐와 힙](https://www.youtube.com/watch?v=AjFlp951nz0&list=PLRx0vPvlEmdAghTr5mXQxGpHjWqSz0dgC&index=11)
  - [ ] [보석도둑](https://www.acmicpc.net/problem/1202)
- [ ] [트리](https://www.youtube.com/watch?v=i5yHkP1jQmo&list=PLRx0vPvlEmdAghTr5mXQxGpHjWqSz0dgC&index=12)
  - [ ] [트리 순회](https://www.acmicpc.net/problem/1991) 
- [ ] [벨만 포드 알고리즘](https://www.youtube.com/watch?v=Ppimbaxm8d8&list=PLRx0vPvlEmdAghTr5mXQxGpHjWqSz0dgC&index=13)
  - [ ]  [타임머신](https://www.acmicpc.net/problem/11657)
- [ ] [바이너리 인덱스 트리, 펜윅 트리](https://www.youtube.com/watch?v=fg2iGP4e2mc&list=PLRx0vPvlEmdAghTr5mXQxGpHjWqSz0dgC&index=14)
  - [ ] [구간 합 구하기](https://www.acmicpc.net/problem/2042)
- [ ] [최소 공통 조상](https://www.youtube.com/watch?v=O895NbxirM8&list=PLRx0vPvlEmdAghTr5mXQxGpHjWqSz0dgC&index=15)
  - [ ] [LCA](https://www.acmicpc.net/problem/11437)
