### ISSUE TITLE
2주차

### ISSUE THREAD

**Issue by JangWooJin1** [Park-Minjoo/CODINGTEST_STUDY#2]
## Description

- 나동빈 강의 진행

## Todo

- 강의 듣기
  - [x] 이진 탐색 - https://www.youtube.com/watch?v=94RC-DsGMLo&list=PLRx0vPvlEmdAghTr5mXQxGpHjWqSz0dgC&index=5
  - [x] dp - https://www.youtube.com/watch?v=5Lu34WIx2Us&list=PLRx0vPvlEmdAghTr5mXQxGpHjWqSz0dgC&index=6
  - [x] 최단 경로 - https://www.youtube.com/watch?v=acqm9mM1P6o&list=PLRx0vPvlEmdAghTr5mXQxGpHjWqSz0dgC&index=7
