### ISSUE TITLE
10주차

### ISSUE THREAD

**Issue by JangWooJin1** [Park-Minjoo/CODINGTEST_STUDY#29]
## Description

- 문제 풀이

## Todo

- DP
  - [ ] [점프](https://www.acmicpc.net/problem/1890)
  - [ ] [양팔저울](https://www.acmicpc.net/problem/2629)
  - [ ] [로또](https://www.acmicpc.net/problem/2758)
