### ISSUE TITLE
11주차

### ISSUE THREAD

**Issue by leemoongi** [Park-Minjoo/CODINGTEST_STUDY#35]
## Todo

- dp 
  - [ ] [평범한 배낭](https://www.acmicpc.net/problem/12865)
  - [ ] [쉬운 계단 수](https://www.acmicpc.net/problem/10844)
  - [ ] [상자넣기](https://www.acmicpc.net/problem/1965)
  - [ ] [수도배관공사](https://www.acmicpc.net/problem/2073)
