### ISSUE TITLE
Week12

### ISSUE THREAD

**Issue by Park-Minjoo** [Park-Minjoo/CODINGTEST_STUDY#38]
## Description

- 문제 풀이

## Todo

- 그래프 탐색 (DFS/BFS)
  - [ ] [뱀과 사다리 게임](https://www.acmicpc.net/problem/16928)
  - [ ] [효율적인 해킹 (실버1)](https://www.acmicpc.net/problem/1325)
  - [ ] [단지번호붙이기 (실버1)](https://www.acmicpc.net/problem/2667)
  - [ ] [연구소 (골드4)](https://www.acmicpc.net/problem/14502)
