### ISSUE TITLE
Week15

### ISSUE THREAD

**Issue by yeonkkk** [Park-Minjoo/CODINGTEST_STUDY#53]
## Description

- 문제 풀이

## Todo

- 구현
  - [ ] [기차가 어둠을 헤치고 은하수를(실버2)](https://www.acmicpc.net/problem/15787)
  - [ ] [오리 (실버2)](https://www.acmicpc.net/problem/12933)
  - [ ] [상어 초등학교 (골드5)](https://www.acmicpc.net/problem/21608)
  - [ ] [스마트물류](https://softeer.ai/practice/6279)
