### ISSUE TITLE
Week16

### ISSUE THREAD

**Issue by Park-Minjoo** [Park-Minjoo/CODINGTEST_STUDY#55]
## Description

- 문제 풀이

## Todo

- DP
  - [ ] [계단 오르기](https://www.acmicpc.net/problem/2579) (복습)
  - [ ] [스티커](https://www.acmicpc.net/problem/9465) (복습)
- 구현
  - [ ] [오목](https://www.acmicpc.net/problem/2615) (new!)
  - [ ] [달팽이](https://www.acmicpc.net/problem/1913) (복습)
