### ISSUE TITLE
Week17

### ISSUE THREAD

**Issue by JangWooJin1** [Park-Minjoo/CODINGTEST_STUDY#59]
## Description

- 기존 문제 복습 및 새로운 문제 풀이

## Todo

- 자료구조(Stack)
  - [ ] [스택 수열](https://www.acmicpc.net/problem/1874) (new)(실버2)
  - [ ] [괄호의 값](https://www.acmicpc.net/problem/2504) (new)(골드5)
- 구현(Implementation)
  - [ ] [별찍기](https://www.acmicpc.net/problem/10994) (new)(실버4)
  - [ ] [상어초등학교](https://www.acmicpc.net/problem/21608) (복습)(골드5)
