### ISSUE TITLE
4주차

### ISSUE THREAD

**Issue by JangWooJin1** [Park-Minjoo/CODINGTEST_STUDY#6]
## Description

- 이코테 강의 수강

## Todo

- 강의 듣기
  - [x] 기타 그래프 이론 - https://www.youtube.com/watch?v=aOhhNFTIeFI&list=PLRx0vPvlEmdAghTr5mXQxGpHjWqSz0dgC&index=8
  - [x] 코테 빈출 기타 - https://www.youtube.com/watch?v=cswJ1h-How0&list=PLRx0vPvlEmdAghTr5mXQxGpHjWqSz0dgC&index=9
  - [x] 개발형 코테 - https://www.youtube.com/watch?v=d8KPN79UAKA&list=PLRx0vPvlEmdAghTr5mXQxGpHjWqSz0dgC&index=10
