### ISSUE TITLE
Week18

### ISSUE THREAD

**Issue by Park-Minjoo** [Park-Minjoo/CODINGTEST_STUDY#63]
## Description

- 기존 문제 복습 및 새로운 문제 풀이

## Todo

- 큐(Queue)
  - [ ] [카드2](https://www.acmicpc.net/problem/2164) (*new)(실버4)
  - [ ] [회전하는 큐](https://www.acmicpc.net/problem/1021) (*new)(실버3)

- 구현(Implementation)
  - [ ] [빙고](https://www.acmicpc.net/problem/2578) (*new)(실버4)
  - [ ] [빗물](https://www.acmicpc.net/problem/14719) (복습)(골드5)
