### ISSUE TITLE
Week20

### ISSUE THREAD

**Issue by Park-Minjoo** [Park-Minjoo/CODINGTEST_STUDY#70]
## Description

- 기존 문제 복습 및 새로운 문제 풀이

## Todo

- DP
  - [ ] [함께 블록 쌓기](https://www.acmicpc.net/problem/18427) (*new)(골드4)
  - [ ] [평범한 배낭](https://www.acmicpc.net/problem/12865) (복습)(골드4)

- 구현(Implementation)
  - [ ] [배열 돌리기](https://www.acmicpc.net/problem/17276) (*new)(실버2)
  - [ ] [ZOAC](https://www.acmicpc.net/problem/16719) (*new)(골드5)
