### ISSUE TITLE
Week21

### ISSUE THREAD

**Issue by Park-Minjoo** [Park-Minjoo/CODINGTEST_STUDY#78]
## Description

- 기존 문제 복습 및 새로운 문제 풀이

## Todo

- 이진탐색
  - [ ] [나무자르기](https://www.acmicpc.net/problem/2805) (복습)(실버2)
  - [ ] [두 용액](https://www.acmicpc.net/problem/2470) (*new)(골드5)

- 구간합
  - [ ] [점수 따먹기](https://www.acmicpc.net/problem/1749) (*new)(골드4)
  - [ ] [피아노 체조](https://www.acmicpc.net/problem/21318) (*new)(실버1)
