### ISSUE TITLE
Week22

### ISSUE THREAD

**Issue by yeonkkk** [Park-Minjoo/CODINGTEST_STUDY#82]
## Description

-  문제를 풀어요 ~~

## Todo

- 시뮬레이션
  - [ ] [학부연구생 민상 (골드5)](https://www.acmicpc.net/problem/21922)
  - [ ] [인내의 도미노 장인 호석 (골드5)](https://www.acmicpc.net/problem/20165)
- 트리
  - [ ] [완전 이진 트리 (실버1)](https://www.acmicpc.net/problem/9934)
  - [ ] [트리 (골드5)](https://www.acmicpc.net/problem/1068)
