### ISSUE TITLE
Week 24

### ISSUE THREAD

**Issue by yeonkkk** [Park-Minjoo/CODINGTEST_STUDY#88]
## Description

- 문제 풀어봐요!

## Todo

- 시뮬레이션
  - [ ] [캐슬 디펜스 ( 골드3 )](https://www.acmicpc.net/problem/17135)
  - [ ] [감시 (골드3)](https://www.acmicpc.net/problem/15683)

- 구현
  - [ ] [단어 맞추기 (실버 1)](https://www.acmicpc.net/problem/9081)

**Comment by yeonkkk** [comment]
다음주 문제는 프로그래머스에서 찾기!

**Comment by Park-Minjoo** [comment]
안푸는 사람 .. 벌금 ..🥹
